console.log("*********** strings**********");
var myName = "yogesh";
console.log("myName:",myName);
console.log("typeof variable myName:",typeof myName);
var middleName = "Dhondiba";
console.log("middleName:",middleName);
console.log("typeof variable middleName:",typeof middleName);
var lastName= "Chandramadne";
console.log("lastName:",lastName);
console.log("typeof variable lastName:",typeof lastName);
console.log("************ Numbers*********");
var mobileNo = 9874563210;
console.log("mobileNo:",mobileNo);
console.log("typeof mobileNo:",typeof mobileNo);
var age = 28;
console.log("age:",age);
console.log("typeof age:",typeof age);
var pinCode = 441750;
console.log("pinCode:",pinCode);
console.log("typeof pinCode:",typeof pinCode);
console.log("********** Boolean***********");
var graduate= true;
console.log(" graduate:", graduate);
console.log("typeof variable graduate:",typeof  graduate);
var ismarried =false;
console.log("ismarried:",ismarried);
console.log("typeof variable ismarried:",typeof ismarried);
var isJobless = false;
console.log(" isJobless :", isJobless );
console.log("typeof  variable isJobless:",typeof isJobless);
console.log("*********** null VS undefined*********");
var collage = null;
console.log("collage:",collage);
console.log("typeof variable collage:",typeof collage);
var city;
console.log("city:",city);
console.log("typeof variable city:",typeof city );

